<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>NesDebugView</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputType>WinExe</OutputType>
    <Platforms>x64;x86</Platforms>
    <RootNamespace>NesDebugView</RootNamespace>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <Import Project="..\Props\OutputApps.props" />

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net8.0-windows' ">
    <ProjectReference Include="..\Cli.Net8\Wrapper.Net80.vcxproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WpfControl\WpfControl.csproj" />
    <ProjectReference Include="..\NesWpfControl\NesWpfControl.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Views/MainWindow.xaml.vb" />
  </ItemGroup>

</Project>
